spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
---
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR